### ISSUE TITLE
Your Firefox profile cannot be loaded. It may be missing or inaccessible.

### ISSUE THREAD

**Issue by andre-santos1** [Jasawn/python-instagram-story-visualiser#1]
Whenever I click "Start scraping..." a small window pops up alerting: "Your Firefox profile cannot be loaded. It may be missing or inaccessible."

I tried with both Firefox and Chrome.

**Comment by Jasawn** [comment]
Hey, there might be something wrong with your firefox. Do check these links out and see if the issues still persist.
https://support.mozilla.org/en-US/questions/1327628
https://support.mozilla.org/en-US/kb/how-run-firefox-when-profile-missing-inaccessible#
